-- AlterTable
ALTER TABLE `profile` ADD COLUMN `company_name` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `shipment` MODIFY `status` ENUM('PENDING', 'IN_PROGRESS', 'IN_TRANSIT', 'DELAYED', 'DELIVERED', 'CANCELLED', 'SUSPENDED') NOT NULL DEFAULT 'PENDING';
